# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logviewer < Formula
  desc ""
  homepage ""
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bascanada/logviewer/releases/download/v0.1.5/logviewer_Darwin_x86_64.tar.gz"
      sha256 "2e1831b51d1d5f7de1829296254b95f02c838a798b2819521b4bd67cf1a2d4d1"

      def install
        bin.install "logviewer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bascanada/logviewer/releases/download/v0.1.5/logviewer_Darwin_arm64.tar.gz"
      sha256 "d6a158289c1c3a1e86d5d1c075e1693ddcd7aa814815542d5c5debebddd5f61a"

      def install
        bin.install "logviewer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bascanada/logviewer/releases/download/v0.1.5/logviewer_Linux_x86_64.tar.gz"
      sha256 "50a9a304ddbeae805744b83fa47f5e5e0728c6cd93ad68e64aa693313e091194"
      def install
        bin.install "logviewer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bascanada/logviewer/releases/download/v0.1.5/logviewer_Linux_arm64.tar.gz"
      sha256 "7c8152e511ed5c9fe9843fd90a30986e90f91f202d268baa742a408da1162d7b"
      def install
        bin.install "logviewer"
      end
    end
  end
end
