# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logviewer < Formula
  desc ""
  homepage ""
  version "0.1.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bascanada/logviewer/releases/download/v0.1.10/logviewer_Darwin_x86_64.tar.gz"
      sha256 "1759a271a766c5044a2c5dcb80b1d6ea3b6741bfc81a72fc075eb4334820ee2c"

      def install
        bin.install "logviewer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bascanada/logviewer/releases/download/v0.1.10/logviewer_Darwin_arm64.tar.gz"
      sha256 "cc1f843ddeeb69d49e2e9eb36fd5ee69425980c3f3d9ac05c6310d9bdbfc1f77"

      def install
        bin.install "logviewer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bascanada/logviewer/releases/download/v0.1.10/logviewer_Linux_x86_64.tar.gz"
      sha256 "c9c155e9c3fd6f820c07edc255e361ff3496d8953c3582d0eca7cc85034fd929"
      def install
        bin.install "logviewer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bascanada/logviewer/releases/download/v0.1.10/logviewer_Linux_arm64.tar.gz"
      sha256 "679b5b251b317966260e07bfbc596f5bf07d9382f1159a0c7881ff53cacbc639"
      def install
        bin.install "logviewer"
      end
    end
  end
end
