# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logviewer < Formula
  desc ""
  homepage ""
  version "0.1.21"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/estran-studio/logviewer/releases/download/v0.1.21/logviewer_Darwin_x86_64.tar.gz"
      sha256 "1bc3b3f854bad57aedb35b403e3c1aaef9be515452197f8aa941fab51ac4516a"

      define_method(:install) do
        bin.install "logviewer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/estran-studio/logviewer/releases/download/v0.1.21/logviewer_Darwin_arm64.tar.gz"
      sha256 "3ad67229d70413e33ed9a83996d0a5cc18c3e63e52f486ee663e0009d608866a"

      define_method(:install) do
        bin.install "logviewer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/estran-studio/logviewer/releases/download/v0.1.21/logviewer_Linux_x86_64.tar.gz"
      sha256 "e9f6b5bbd4ba9d2d31a19d53fef78f911c27555ef838d081ea7d0f373fff337e"
      define_method(:install) do
        bin.install "logviewer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/estran-studio/logviewer/releases/download/v0.1.21/logviewer_Linux_arm64.tar.gz"
      sha256 "877c98ac7485b818cbc03dffe804f530ce11eba7bcf3b0239c54d8e73d43a493"
      define_method(:install) do
        bin.install "logviewer"
      end
    end
  end
end
